import { Exercicio, Treino } from "../models/Exercicio";

export const workoutPlans: Treino[] = [
  {
    id: 1,
    nome: "Push 1",
    observacao: "",
    exercicios: [
      {
        id: 1,
        nome: "Supino Inclinado com Halteres",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 2,
        nome: "Supino Reto na Máquina",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 3,
        nome: "Crucifixo na Máquina (Pec Deck)",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 4,
        nome: "Desenvolvimento com Barra",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 5,
        nome: "Elevação Lateral",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 6,
        nome: "Extensões de Tríceps Overhead",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 7,
        nome: "Extensões de Tríceps com Corda",
        observacao: "3 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
    ],
  },
  {
    id: 2,
    nome: "Pull 1",
    observacao: "",
    exercicios: [
      {
        id: 8,
        nome: "Pulldown (Puxada Frontal)",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 9,
        nome: "Pullover com Barra ou Halteres",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 10,
        nome: "Remada Aberta na Barra",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 11,
        nome: "Encolhimento de Ombros (Shrugs)",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 12,
        nome: "Crucifixo Invertido na Máquina (Pec Deck Invertido)",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 13,
        nome: "Rosca Martelo",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 14,
        nome: "Rosca no Banco Scott",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
    ],
  },
  {
    id: 3,
    nome: "Legs 1",
    observacao: "",
    exercicios: [
      {
        id: 15,
        nome: "Agachamento Hack",
        observacao: "3 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 16,
        nome: "Levantamento Terra Romeno",
        observacao: "3 séries de 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 17,
        nome: "Extensão de Pernas na Máquina",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 18,
        nome: "Flexão de Pernas Sentado na Máquina",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 19,
        nome: "Elevação de Panturrilha em Pé",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 20,
        nome: "Abdominais Decline",
        observacao: "3 séries até a falha",
        imagem: "",
        video: "",
      },
      {
        id: 21,
        nome: "Elevação de Pernas",
        observacao: "3 séries até a falha",
        imagem: "",
        video: "",
      },
    ],
  },
  {
    id: 4,
    nome: "Push 2",
    observacao: "",
    exercicios: [
      {
        id: 1,
        nome: "Supino Inclinado na Smith",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 2,
        nome: "Supino Reto na Máquina",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 3,
        nome: "Crucifixo no Cabo",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 4,
        nome: "Desenvolvimento de Ombros Sentado com Halteres",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 5,
        nome: "Elevação Lateral",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 6,
        nome: "Extensões de Tríceps com Corda",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 7,
        nome: "Skullcrusher com Barra EZ ",
        observacao: "3 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
    ],
  },
  {
    id: 5,
    nome: "Pull 2",
    observacao: "",
    exercicios: [
      {
        id: 8,
        nome: "Pulldown com Pegada Fechada",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 9,
        nome: "Remada Sentada na Máquina com Pegada Unilateral",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 10,
        nome: "Encolhimento de Ombros (Shrugs)",
        observacao: "4 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 11,
        nome: "Crucifixo Invertido no Cabo",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 12,
        nome: "Rosca Direta",
        observacao: "3 séries de 12 a 15 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 13,
        nome: "Rosca Martelo",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
    ],
  },
  {
    id: 6,
    nome: "Legs 2",
    observacao: "",
    exercicios: [
      {
        id: 15,
        nome: "Agachamento Hack",
        observacao: "3 séries de 8 a 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 16,
        nome: "Levantamento Terra Romeno",
        observacao: "3 séries de 10 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 17,
        nome: "Extensão de Pernas na Máquina",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 18,
        nome: "Flexão de Pernas Sentado na Máquina",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 19,
        nome: "Elevação de Panturrilha em Pé",
        observacao: "3 séries de 10 a 12 repetições",
        imagem: "",
        video: "",
      },
      {
        id: 20,
        nome: "Abdominais Decline",
        observacao: "3 séries até a falha",
        imagem: "",
        video: "",
      },
      {
        id: 21,
        nome: "Elevação de Pernas",
        observacao: "3 séries até a falha",
        imagem: "",
        video: "",
      },
    ],
  },
];
